apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "myapp"
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: "myapp"
      labels:
           app: myapp
           phase: production
    spec:
      containers:
        - name: "nginx"
          image: sliranc/myapp:latest 
          ports:
            - name: "nginx-port"
              containerPort: 80
