   apiVersion: "extensions/v1beta1"
   kind: "Deployment"
   metadata:
     name: "myapp"
   spec:
     replicas: 3
     template:
       metadata:
         name: "myapp"
         labels:
              app: myapp
              phase: production
       spec:
         containers:
           - name: "nginx"
             image: sliranc/rcweb:latest 
             ports:
               - name: "nginx-port"
                 containerPort: 80
