apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirstrc
  labels: 
    name: myfirstrc
spec:
  replicas: 2
  # selector identifies the set of pods that this
  # replication controller is responsible for managing
  selector:
    name: myfirstrcpod
  # template defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        phase: prod
        role: frontend
        name: myfirstpod
      name: myfirstpod
    spec:
      containers:
      - name: filepuller
        image: sliranc/filepuller:latest
        volumeMounts:
        - mountPath: /static
          name: static-vol
      - name: webserver
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html/static
            name: static-vol
      volumes:
      - name: static-vol
        emptyDir: {}
