apiVersion: v1
kind: Pod
metadata:
  labels:
    phase: prod
    role: frontend
    name: myfirstpod
  name: myfirstpod
spec:
  containers:
  - name: filepuller
    image: sliranc/filepuller:latest
    volumeMounts:
    - mountPath: /static
      name: static-vol
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /var/www/html/static
        name: static-vol
  volumes:
  - name: static-vol
    emptyDir: {}
